name: koye_kos
description: Find and recommend awesome hammocing spots

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase/Google
  firebase_core: ^0.4.5
  firebase_analytics: ^5.0.16
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  google_sign_in: ^4.5.1
  firebase_storage: ^3.1.6

  # State
  provider: ^4.3.1

  # Flutter map
  flutter_map: ^0.10.1

  # image
  image_picker: ^0.6.7+4
  cached_network_image: ^2.3.0-rc
  transparent_image: ^1.0.0
  image_cropper: ^1.2.3
  photo_view: ^0.9.2
  flutter_image_compress: ^0.7.0

  # Misc
  animations: ^1.1.2
  font_awesome_flutter: ^8.8.1
  # smooth_star_rating: 1.1.1

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
