name: koye_kos
description: Find and recommend awesome hammocing spots

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase/Google
  firebase_core: ^0.5.0
  firebase_analytics: ^6.0.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+1
  google_sign_in: ^4.5.1
  firebase_storage: ^4.0.0

  # State
  provider: ^4.3.1

  # Flutter map
  mapbox_gl: ^0.8.0
  latlong: ^0.6.1
  location: ^3.0.2

  # image
  image_picker: ^0.6.7+7
  cached_network_image: ^2.3.1
  transparent_image: ^1.0.0
  image_cropper: ^1.2.3
  photo_view: ^0.10.2
  flutter_image_compress: ^0.7.0

  # Misc
  animations: ^1.1.2
  font_awesome_flutter: ^8.8.1
  implicitly_animated_reorderable_list: ^0.2.3
  connectivity: ^0.4.9+2

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
